use atomic_core::event::{Event, EventPayload, OrderAckEvent, OrderFillEvent, OrderNewEvent, OrderRejectEvent};
use atomic_core::types::{Level, OrderId, OrderType, Price, Qty, Side, Symbol, TimeInForce, Venue};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap, VecDeque};

/// Configuration for the simulated exchange.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SimulatorConfig {
    /// Simulated latency for order acknowledgment (nanoseconds).
    pub ack_latency_ns: u64,
    /// Simulated latency for fill generation (nanoseconds).
    pub fill_latency_ns: u64,
    /// Maker fee in basis points (e.g., 2 = 0.02%).
    pub maker_fee_bps: i64,
    /// Taker fee in basis points (e.g., 5 = 0.05%).
    pub taker_fee_bps: i64,
}

impl Default for SimulatorConfig {
    fn default() -> Self {
        Self {
            ack_latency_ns: 1_000_000,  // 1ms
            fill_latency_ns: 5_000_000, // 5ms
            maker_fee_bps: 2,
            taker_fee_bps: 5,
        }
    }
}

/// A pending order resting in the simulated order book.
#[derive(Debug, Clone)]
#[allow(dead_code)]
struct SimOrder {
    order_id: OrderId,
    symbol: Symbol,
    side: Side,
    order_type: OrderType,
    price: Price,
    qty: Qty,
    remaining: u64,
    time_in_force: TimeInForce,
    submitted_at: u64,
    source: [u8; 32],
}

/// Internal order book for matching.
struct SimBook {
    bids: BTreeMap<i64, u64>,
    asks: BTreeMap<i64, u64>,
}

impl SimBook {
    fn new() -> Self {
        Self {
            bids: BTreeMap::new(),
            asks: BTreeMap::new(),
        }
    }

    fn apply_levels(&mut self, bids: &[Level], asks: &[Level], is_snapshot: bool) {
        if is_snapshot {
            self.bids.clear();
            self.asks.clear();
        }
        for l in bids {
            if l.qty.0 == 0 {
                self.bids.remove(&l.price.0);
            } else {
                self.bids.insert(l.price.0, l.qty.0);
            }
        }
        for l in asks {
            if l.qty.0 == 0 {
                self.asks.remove(&l.price.0);
            } else {
                self.asks.insert(l.price.0, l.qty.0);
            }
        }
    }
}

/// Fill generated by the matching engine.
struct MatchFill {
    price: i64,
    qty: u64,
}

/// Result of a match attempt.
struct MatchResult {
    fills: Vec<MatchFill>,
    remaining: u64,
}

/// Match an order against one side of the book, consuming liquidity.
fn match_order(
    book_side: &mut BTreeMap<i64, u64>,
    side: Side,
    qty: u64,
    limit_price: Option<i64>,
) -> MatchResult {
    let mut remaining = qty;
    let mut fills = Vec::new();

    // Collect prices to iterate (buy matches against asks ascending, sell against bids descending)
    let prices: Vec<i64> = match side {
        Side::Buy => book_side.keys().copied().collect(),
        Side::Sell => book_side.keys().rev().copied().collect(),
    };

    for price in prices {
        if remaining == 0 {
            break;
        }
        if let Some(limit) = limit_price {
            match side {
                Side::Buy if price > limit => break,
                Side::Sell if price < limit => break,
                _ => {}
            }
        }
        let avail = match book_side.get(&price) {
            Some(&q) => q,
            None => continue,
        };
        let fill_qty = remaining.min(avail);
        if fill_qty > 0 {
            remaining -= fill_qty;
            let new_avail = avail - fill_qty;
            if new_avail == 0 {
                book_side.remove(&price);
            } else {
                book_side.insert(price, new_avail);
            }
            fills.push(MatchFill { price, qty: fill_qty });
        }
    }

    MatchResult { fills, remaining }
}

/// Simulated exchange with order matching engine.
///
/// Accepts orders, matches them against an internal order book fed by market data,
/// and generates deterministic ack/fill events. Used for backtesting without
/// connecting to a real exchange.
pub struct SimulatedExchange {
    config: SimulatorConfig,
    books: HashMap<String, SimBook>,
    resting_orders: HashMap<String, SimOrder>,
    pending_events: VecDeque<Event>,
    next_exchange_id: u64,
}

impl SimulatedExchange {
    pub fn new(config: SimulatorConfig) -> Self {
        Self {
            config,
            books: HashMap::new(),
            resting_orders: HashMap::new(),
            pending_events: VecDeque::new(),
            next_exchange_id: 1,
        }
    }

    /// Feed market data into the simulator (updates the internal book).
    pub fn on_book_update(
        &mut self,
        symbol: &Symbol,
        bids: &[Level],
        asks: &[Level],
        is_snapshot: bool,
    ) {
        let key = symbol.pair();
        let book = self.books.entry(key.clone()).or_insert_with(SimBook::new);
        book.apply_levels(bids, asks, is_snapshot);

        // Check resting limit orders that may now cross
        self.check_resting_orders(&key);
    }

    /// Submit an order to the simulated exchange.
    pub fn submit_order(&mut self, order: &OrderNewEvent, timestamp: u64, source: [u8; 32]) {
        let key = order.symbol.pair();
        let ack_ts = timestamp + self.config.ack_latency_ns;
        let fill_ts = timestamp + self.config.fill_latency_ns;
        let limit_price = match order.order_type {
            OrderType::Market => None,
            OrderType::Limit | OrderType::StopLimit => Some(order.price.0),
            OrderType::StopMarket => None,
        };

        // FillOrKill: verify full liquidity is available before touching the book.
        if order.time_in_force == TimeInForce::FillOrKill {
            let available: u64 = self.books.get(&key).map_or(0, |book| {
                let side = match order.side {
                    Side::Buy => &book.asks,
                    Side::Sell => &book.bids,
                };
                side.iter()
                    .filter(|(&p, _)| match order.side {
                        Side::Buy => limit_price.map_or(true, |lp| p <= lp),
                        Side::Sell => limit_price.map_or(true, |lp| p >= lp),
                    })
                    .map(|(_, &q)| q)
                    .sum()
            });
            if available < order.qty.0 {
                self.pending_events.push_back(Event::new(
                    0, ack_ts, source,
                    EventPayload::OrderReject(OrderRejectEvent {
                        order_id: order.order_id.clone(),
                        reason: "fok_unfillable".to_string(),
                        venue: Venue::Simulated,
                    }),
                ));
                return;
            }
        }

        // Market order: reject immediately if no liquidity on the matching side.
        if order.order_type == OrderType::Market {
            let has_liquidity = self.books.get(&key).map_or(false, |book| match order.side {
                Side::Buy => !book.asks.is_empty(),
                Side::Sell => !book.bids.is_empty(),
            });
            if !has_liquidity {
                self.pending_events.push_back(Event::new(
                    0, ack_ts, source,
                    EventPayload::OrderReject(OrderRejectEvent {
                        order_id: order.order_id.clone(),
                        reason: "no_liquidity".to_string(),
                        venue: Venue::Simulated,
                    }),
                ));
                return;
            }
        }

        // Generate ack.
        let exchange_id = format!("SIM-{}", self.next_exchange_id);
        self.next_exchange_id += 1;
        self.pending_events.push_back(Event::new(
            0, ack_ts, source,
            EventPayload::OrderAck(OrderAckEvent {
                order_id: order.order_id.clone(),
                exchange_order_id: exchange_id,
                venue: Venue::Simulated,
            }),
        ));

        // Match against book.
        let result = if let Some(book) = self.books.get_mut(&key) {
            let book_side = match order.side {
                Side::Buy => &mut book.asks,
                Side::Sell => &mut book.bids,
            };
            match_order(book_side, order.side, order.qty.0, limit_price)
        } else {
            MatchResult { fills: Vec::new(), remaining: order.qty.0 }
        };

        // Generate fill events, decrementing remaining correctly after each fill.
        let mut remaining = order.qty.0;
        for fill in &result.fills {
            remaining = remaining.saturating_sub(fill.qty);
            let fee = (fill.price * fill.qty as i64 * self.config.taker_fee_bps) / 10_000;
            self.pending_events.push_back(Event::new(
                0, fill_ts, source,
                EventPayload::OrderFill(OrderFillEvent {
                    order_id: order.order_id.clone(),
                    symbol: order.symbol.clone(),
                    side: order.side,
                    price: Price(fill.price),
                    qty: Qty(fill.qty),
                    remaining: Qty(remaining),
                    fee,
                    is_maker: false,
                    venue: Venue::Simulated,
                }),
            ));
        }

        // Handle unfilled remaining qty.
        if result.remaining > 0 {
            match order.time_in_force {
                TimeInForce::ImmediateOrCancel => {
                    // Cancel the unfilled portion immediately.
                    self.pending_events.push_back(Event::new(
                        0, fill_ts, source,
                        EventPayload::OrderCancel(atomic_core::event::OrderCancelEvent {
                            order_id: order.order_id.clone(),
                            reason: "ioc_expired".to_string(),
                            venue: Venue::Simulated,
                        }),
                    ));
                }
                TimeInForce::GoodTilCancel | TimeInForce::GoodTilDate(_)
                    if order.order_type == OrderType::Limit =>
                {
                    self.resting_orders.insert(
                        order.order_id.0.clone(),
                        SimOrder {
                            order_id: order.order_id.clone(),
                            symbol: order.symbol.clone(),
                            side: order.side,
                            order_type: order.order_type,
                            price: order.price,
                            qty: order.qty,
                            remaining: result.remaining,
                            time_in_force: order.time_in_force,
                            submitted_at: timestamp,
                            source,
                        },
                    );
                }
                _ => {}
            }
        }
    }

    /// Cancel a resting order.
    pub fn cancel_order(&mut self, order_id: &OrderId, timestamp: u64, source: [u8; 32]) {
        if self.resting_orders.remove(&order_id.0).is_some() {
            self.pending_events.push_back(Event::new(
                0,
                timestamp + self.config.ack_latency_ns,
                source,
                EventPayload::OrderCancel(atomic_core::event::OrderCancelEvent {
                    order_id: order_id.clone(),
                    reason: "user_cancel".to_string(),
                    venue: Venue::Simulated,
                }),
            ));
        }
    }

    /// Check resting limit orders after book update.
    fn check_resting_orders(&mut self, pair_key: &str) {
        let order_ids: Vec<String> = self
            .resting_orders
            .iter()
            .filter(|(_, o)| o.symbol.pair() == pair_key)
            .map(|(id, _)| id.clone())
            .collect();

        for oid in order_ids {
            let order = match self.resting_orders.get(&oid) {
                Some(o) => o.clone(),
                None => continue,
            };

            let limit = order.price.0;
            // Passive maker fill: check if market crosses our resting level
            let can_cross = if let Some(book) = self.books.get(&order.symbol.pair()) {
                match order.side {
                    Side::Buy => book.asks.keys().next().map_or(false, |&p| p <= limit),
                    Side::Sell => book.bids.keys().next_back().map_or(false, |&p| p >= limit),
                }
            } else {
                false
            };

            if !can_cross {
                continue;
            }

            // Passive maker fill at our limit price (not at the market's price)
            let fill_ts = order.submitted_at + self.config.fill_latency_ns;
            let fill_qty = order.remaining;
            let fee =
                (limit * fill_qty as i64 * self.config.maker_fee_bps) / 10_000;
            self.pending_events.push_back(Event::new(
                0,
                fill_ts,
                order.source,
                EventPayload::OrderFill(OrderFillEvent {
                    order_id: order.order_id.clone(),
                    symbol: order.symbol.clone(),
                    side: order.side,
                    price: Price(limit),
                    qty: Qty(fill_qty),
                    remaining: Qty(0),
                    fee,
                    is_maker: true,
                    venue: Venue::Simulated,
                }),
            ));

            self.resting_orders.remove(&oid);
        }
    }

    /// Drain all pending events, assigning sequence numbers starting from `start_seq`.
    pub fn drain_events(&mut self, start_seq: u64) -> Vec<Event> {
        let mut seq = start_seq;
        let mut events = Vec::new();
        while let Some(mut event) = self.pending_events.pop_front() {
            event.seq = seq;
            seq += 1;
            events.push(event);
        }
        events
    }

    pub fn pending_count(&self) -> usize {
        self.pending_events.len()
    }

    pub fn resting_order_count(&self) -> usize {
        self.resting_orders.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sym() -> Symbol {
        Symbol::new("BTC", "USDT", Venue::Simulated)
    }

    fn setup_book(exchange: &mut SimulatedExchange) {
        let asks = vec![
            Level { price: Price(60100), qty: Qty(50) },
            Level { price: Price(60200), qty: Qty(100) },
            Level { price: Price(60300), qty: Qty(200) },
        ];
        let bids = vec![
            Level { price: Price(60000), qty: Qty(80) },
            Level { price: Price(59900), qty: Qty(150) },
        ];
        exchange.on_book_update(&sym(), &bids, &asks, true);
    }

    #[test]
    fn market_buy_fills_asks() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        setup_book(&mut exchange);

        let order = OrderNewEvent {
            order_id: OrderId::new(Venue::Simulated, 1),
            symbol: sym(),
            side: Side::Buy,
            order_type: OrderType::Market,
            price: Price(0),
            qty: Qty(70),
            time_in_force: TimeInForce::ImmediateOrCancel,
            venue: Venue::Simulated,
        };

        exchange.submit_order(&order, 1000, [0u8; 32]);
        let events = exchange.drain_events(1);

        // Should have 1 ack + fills
        assert!(events.len() >= 2);
        // First event is ack
        assert!(matches!(events[0].payload, EventPayload::OrderAck(_)));
        // Second is fill (50 from first level, 20 from second)
        assert!(matches!(events[1].payload, EventPayload::OrderFill(_)));
    }

    #[test]
    fn limit_order_rests_if_no_cross() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        setup_book(&mut exchange);

        let order = OrderNewEvent {
            order_id: OrderId::new(Venue::Simulated, 1),
            symbol: sym(),
            side: Side::Buy,
            order_type: OrderType::Limit,
            price: Price(59800), // below best ask, won't cross
            qty: Qty(100),
            time_in_force: TimeInForce::GoodTilCancel,
            venue: Venue::Simulated,
        };

        exchange.submit_order(&order, 1000, [0u8; 32]);
        let events = exchange.drain_events(1);

        // Only ack, no fills
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0].payload, EventPayload::OrderAck(_)));
        assert_eq!(exchange.resting_order_count(), 1);
    }

    #[test]
    fn resting_limit_fills_on_book_update() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        setup_book(&mut exchange);

        // Place limit buy below current ask
        let order = OrderNewEvent {
            order_id: OrderId::new(Venue::Simulated, 1),
            symbol: sym(),
            side: Side::Buy,
            order_type: OrderType::Limit,
            price: Price(59800),
            qty: Qty(50),
            time_in_force: TimeInForce::GoodTilCancel,
            venue: Venue::Simulated,
        };
        exchange.submit_order(&order, 1000, [0u8; 32]);
        let _ = exchange.drain_events(1);
        assert_eq!(exchange.resting_order_count(), 1);

        // Asks drop below our limit — resting order should fill
        let new_asks = vec![
            Level { price: Price(59700), qty: Qty(200) },
        ];
        exchange.on_book_update(&sym(), &[], &new_asks, true);
        let events = exchange.drain_events(100);

        // Should have fill event
        assert!(!events.is_empty());
        assert!(matches!(events[0].payload, EventPayload::OrderFill(_)));
        assert_eq!(exchange.resting_order_count(), 0);
    }

    #[test]
    fn market_sell_fills_bids() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        setup_book(&mut exchange);

        let order = OrderNewEvent {
            order_id: OrderId::new(Venue::Simulated, 1),
            symbol: sym(),
            side: Side::Sell,
            order_type: OrderType::Market,
            price: Price(0),
            qty: Qty(100),
            time_in_force: TimeInForce::ImmediateOrCancel,
            venue: Venue::Simulated,
        };

        exchange.submit_order(&order, 2000, [0u8; 32]);
        let events = exchange.drain_events(1);

        assert!(events.len() >= 2); // ack + fills
        assert!(matches!(events[0].payload, EventPayload::OrderAck(_)));
    }

    #[test]
    fn cancel_resting_order() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        setup_book(&mut exchange);

        let oid = OrderId::new(Venue::Simulated, 1);
        let order = OrderNewEvent {
            order_id: oid.clone(),
            symbol: sym(),
            side: Side::Buy,
            order_type: OrderType::Limit,
            price: Price(59000),
            qty: Qty(100),
            time_in_force: TimeInForce::GoodTilCancel,
            venue: Venue::Simulated,
        };
        exchange.submit_order(&order, 1000, [0u8; 32]);
        let _ = exchange.drain_events(1);
        assert_eq!(exchange.resting_order_count(), 1);

        exchange.cancel_order(&oid, 2000, [0u8; 32]);
        let events = exchange.drain_events(100);
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0].payload, EventPayload::OrderCancel(_)));
        assert_eq!(exchange.resting_order_count(), 0);
    }

    #[test]
    fn ioc_cancel_on_partial_fill() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        setup_book(&mut exchange);

        // Limit IOC buy at 60100 — only first ask level (50 qty) crosses; remaining 30 → cancel
        let order = OrderNewEvent {
            order_id: OrderId::new(Venue::Simulated, 1),
            symbol: sym(),
            side: Side::Buy,
            order_type: OrderType::Limit,
            price: Price(60100),
            qty: Qty(80),
            time_in_force: TimeInForce::ImmediateOrCancel,
            venue: Venue::Simulated,
        };

        exchange.submit_order(&order, 1000, [0u8; 32]);
        let events = exchange.drain_events(1);

        // ack + fill(s) + cancel
        assert!(events.len() >= 3);
        assert!(matches!(events[0].payload, EventPayload::OrderAck(_)));
        let has_cancel = events.iter().any(|e| matches!(e.payload, EventPayload::OrderCancel(_)));
        assert!(has_cancel, "IOC should cancel unfilled qty");
        assert_eq!(exchange.resting_order_count(), 0, "IOC must not rest");
    }

    #[test]
    fn market_reject_on_empty_book() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        // No book loaded

        let order = OrderNewEvent {
            order_id: OrderId::new(Venue::Simulated, 1),
            symbol: sym(),
            side: Side::Buy,
            order_type: OrderType::Market,
            price: Price(0),
            qty: Qty(10),
            time_in_force: TimeInForce::ImmediateOrCancel,
            venue: Venue::Simulated,
        };

        exchange.submit_order(&order, 1000, [0u8; 32]);
        let events = exchange.drain_events(1);

        assert_eq!(events.len(), 1);
        assert!(matches!(events[0].payload, EventPayload::OrderReject(_)));
    }

    #[test]
    fn fok_reject_if_insufficient_liquidity() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        setup_book(&mut exchange); // asks total: 50 + 100 + 200 = 350

        let order = OrderNewEvent {
            order_id: OrderId::new(Venue::Simulated, 1),
            symbol: sym(),
            side: Side::Buy,
            order_type: OrderType::Market,
            price: Price(0),
            qty: Qty(500), // more than available
            time_in_force: TimeInForce::FillOrKill,
            venue: Venue::Simulated,
        };

        exchange.submit_order(&order, 1000, [0u8; 32]);
        let events = exchange.drain_events(1);

        assert_eq!(events.len(), 1);
        assert!(matches!(events[0].payload, EventPayload::OrderReject(_)));
    }

    #[test]
    fn fill_remaining_decrements_correctly() {
        let mut exchange = SimulatedExchange::new(SimulatorConfig::default());
        // Two ask levels: 60100 x 50, 60200 x 100
        let asks = vec![
            Level { price: Price(60100), qty: Qty(50) },
            Level { price: Price(60200), qty: Qty(100) },
        ];
        exchange.on_book_update(&sym(), &[], &asks, true);

        let order = OrderNewEvent {
            order_id: OrderId::new(Venue::Simulated, 1),
            symbol: sym(),
            side: Side::Buy,
            order_type: OrderType::Market,
            price: Price(0),
            qty: Qty(120),
            time_in_force: TimeInForce::ImmediateOrCancel,
            venue: Venue::Simulated,
        };

        exchange.submit_order(&order, 1000, [0u8; 32]);
        let events = exchange.drain_events(1);

        // ack + fill@60100(50, remaining=70) + fill@60200(70, remaining=0)
        let fills: Vec<_> = events.iter()
            .filter_map(|e| if let EventPayload::OrderFill(f) = &e.payload { Some(f) } else { None })
            .collect();
        assert_eq!(fills.len(), 2);
        assert_eq!(fills[0].remaining.0, 70, "after first fill remaining should be 70");
        assert_eq!(fills[1].remaining.0, 0, "after second fill remaining should be 0");
    }
}
